// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lotto-home-community/CommunityService.tsx": () => import("../components/mockups/lotto-home-community/CommunityService.tsx"),
  "./components/mockups/lotto-home-data/DataCenter.tsx": () => import("../components/mockups/lotto-home-data/DataCenter.tsx"),
  "./components/mockups/lotto-home-proof/ProofArchive.tsx": () => import("../components/mockups/lotto-home-proof/ProofArchive.tsx")
};
