// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lotto-footer-redesign/Current.tsx": () => import("../components/mockups/lotto-footer-redesign/Current.tsx"),
  "./components/mockups/lotto-footer-redesign/Refined.tsx": () => import("../components/mockups/lotto-footer-redesign/Refined.tsx"),
  "./components/mockups/lotto-home-community/CommunityService.tsx": () => import("../components/mockups/lotto-home-community/CommunityService.tsx"),
  "./components/mockups/lotto-home-data/DataCenter.tsx": () => import("../components/mockups/lotto-home-data/DataCenter.tsx"),
  "./components/mockups/lotto-home-proof/ProofArchive.tsx": () => import("../components/mockups/lotto-home-proof/ProofArchive.tsx"),
  "./components/mockups/lotto-portal-a/PortalArchive.tsx": () => import("../components/mockups/lotto-portal-a/PortalArchive.tsx"),
  "./components/mockups/lotto-portal-b/PortalAnalysis.tsx": () => import("../components/mockups/lotto-portal-b/PortalAnalysis.tsx"),
  "./components/mockups/lotto-portal-c/PortalUnified.tsx": () => import("../components/mockups/lotto-portal-c/PortalUnified.tsx")
};
